[package]
name = "words_counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "rwc"
path = "src/main.rs"

[lib]
name = "wordcount"

[dependencies]
thiserror = "1.0.31"
anyhow = "1.0.58"